### ISSUE TITLE
Covering or Ignoring Generated Functions

### ISSUE THREAD

**Issue by jsmylnycky** [deepsweet/istanbul-instrumenter-loader#11]
Hi,

I have a setup using Webpack with Babel and this project, and while everything works great, one issue I've been trying to figure out how to fix is the coverage occurring on the generated functions.

Functions such as  _createClass and _classCallCheck end up tanking my coverage stats, especially for Branches.

Is there something I may have done incorrectly? Is there a way to ignore these generated functions from being covered?  Is this on a roadmap anywhere for resolution? 

Thanks!

**Comment by aaronmaturen** [comment]
+1

**Comment by deepsweet** [comment]
hi.

are you talking about ES6 code transpiled by Babel?

**Comment by jsmylnycky** [comment]
Yup, those functions at the top of each file after Babel transpiles ES6.
They end up counting against the coverage.

**Comment by deepsweet** [comment]
you can cover original ES6 code with https://github.com/deepsweet/isparta-loader

**Comment by jsmylnycky** [comment]
Thanks, I'll take a look at that in the morning and post back here if
there's any issues :). Hard to find an answer to this issue.

**Comment by deepsweet** [comment]
I'll update README with note about this. Isparta "binds" transpiled constructions to your original ES6 lines of code, so coverage report will be fair.

**Comment by jsmylnycky** [comment]
Thanks!

**Comment by jsmylnycky** [comment]
@deepsweet  Just an FYI, I did just plug in isparta and moved it from post to pre-loader, and everything covers 100% now.  Thanks so much :)
