### ISSUE TITLE
Pass "noCompact" option

### ISSUE THREAD

**Issue by benderTheCrime** [deepsweet/istanbul-instrumenter-loader#20]
Is there a way to specify a query, similar to other loaders, where I could tell the instrumenter to use the istanbul "noCompact" option?

Similar to:

```
    {
        test: /\.js?$/,
        exclude: /node_modules/,
        loader: 'istanbul-instrumenter',
        query: {
            instrumenterOptions: {
                istanbul: { noCompact: true }
            }
        }
    }
```

or as a stringified query on the loader string itself?

**Comment by benderTheCrime** [comment]
It looks like no...based on the code. Is there any way you can add a PR to extend the options you pass by default by an addition query passed to the loader?

**Comment by deepsweet** [comment]
```js
query: {
    noCompact: true
}
```
