### ISSUE TITLE
When using as postLoader and Babel as loader, it don't coverage the original source

### ISSUE THREAD

**Issue by gartz** [deepsweet/istanbul-instrumenter-loader#22]
Looks like it's not reading the Babel source-map and it's creating a source-map of the Babel loader result file.

It should refer to the source-map and not to the file it self.

**Comment by gartz** [comment]
This project might be helpful: https://github.com/Cellarise/istanbul-coverage-source-map
So we could run the istanbul with source-map, them babel can source-map over it and it's possible to debug and coverage at same time the tests from a test watch.

**Comment by deepsweet** [comment]
you should not transpile covered sources with babel, it's already transpiled with isparta, see README for usage example. the problem is not in sourcemaps.
