### ISSUE TITLE
istanbul-lib-instrument v1.3.1 breaking change

### ISSUE THREAD

**Issue by Attrash-Islam** [deepsweet/istanbul-instrumenter-loader#37]
The istanbul-lib-instrument last release (v1.3.1) affected the istanbul-instrumenter-loader package with the error message (No changes in my codebase):

PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  SyntaxError: Cannot declare a parameter named 'area'  in strict mode

Removed the package from postLoaders in Webpack configuration.

Was working perfectly on istanbul-lib-instrument v1.3.0 release

**Comment by deepsweet** [comment]
nuff said... please report this to them. I think it's related to some specific peace of code that you have, because the only changes were in `src/visitor.js`

**Comment by Attrash-Islam** [comment]
I already reported to them. There is definitely ZERO changes in my source code.

Thanks

**Comment by deepsweet** [comment]
so what was the bug?

**Comment by Attrash-Islam** [comment]
I didn't receive anything yet, and don't use it in the meanwhile because it's breaking a lot in my TypeScript projects.

But I assume they figure it out from the discussion out there :smiley:
