### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by chrisjlee** [deepsweet/istanbul-instrumenter-loader#39]
WTFPL. lol 

So is there a real license agreement to this? I'm trying to get this package approved for usage and our legal team will probably have a fit about it. 

I can PR and update your license if you require.

**Comment by deepsweet** [comment]
sure, I can change it to MIT. should it be a major version bump? 🤔 May sound like "breaking" changes for someone.

**Comment by chrisjlee** [comment]
No probably not a breaking change. I guess technically a patch version?

**Comment by filipesilva** [comment]
Heya, I'm in a similar position myself. Over at https://github.com/angular/angular-cli we're trying to get legal approval but WTFL is a no go. MIT would work for us as well.

According to the discussion at https://github.com/mojombo/semver/issues/322 it sounds like a license change should be a major version, yes.

**Comment by deepsweet** [comment]
ok, it will be a major change. sorry for delay, have almost no time for open source now.

**Comment by filipesilva** [comment]
@deepsweet I can put the PR together, would that help?

**Comment by deepsweet** [comment]
yeah, take it from [here](https://github.com/start-runner/start/blob/master/license.md) please, but starting with 2017 year.

**Comment by filipesilva** [comment]
Here it is: https://github.com/deepsweet/istanbul-instrumenter-loader/pull/43
LMK if you also want me to bump the version in the PR.

Cheers!
