### ISSUE TITLE
Coverage report don't catch source files when running on Jenkins

### ISSUE THREAD

**Issue by nilni-ck** [deepsweet/istanbul-instrumenter-loader#6]
Statements   : 100% ( 0/0 )
Branches     : 100% ( 0/0 )
Functions    : 100% ( 0/0 )
Lines        : 100% ( 0/0 )

so everything works fine on mac, then I run this on test server hosting jenkin. Only "test.js" is catched by istanbul, all source files are missing

**Comment by deepsweet** [comment]
are you sure that configurations are the same? I can't even imagine an OS specific problem with this loader.

**Comment by nilni-ck** [comment]
Yes I am using the same config. Actually really wield, it works fine for me on the mac, and even linux (vagrant). but not for jenkin server. Currently I am investigating in that. This is my config file
```js
/* global __dirname */
// Karma configuration
"use strict";

// var path    = require('path');
var webpackConfig = require('../../../docroot/res/webpack.config.js');

function parseDevConfigToTestConfig(config) {
    delete config.entry;
    config.devtool = 'inline-source-map';
    config.module = config.module || {};
    config.module.postLoaders = [ { // << add subject as webpack's postloader
        test: /\.js$/,
        exclude: /(lib|portal|tests|node_modules|bower_components)\//,
        loader: 'istanbul-instrumenter'
    } ];
    return config;
}

var JQUERY = '../../../docroot/res/js/lib/jquery-mobile/jquery-1.9.1.min.js';
var JSROOT = '../../../docroot/res/js/';
var JSTESTROOT = '../docroot/res/js/';

module.exports = function(config) {
  config.set({

    // base path that will be used to resolve` all patterns (eg. files, exclude)
    basePath: '',

    // set browser timeout to a really long number to wait for webpack to complie
    browserNoActivityTimeout: 100000,

    // frameworks to use
    // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
    frameworks: ['jasmine'],


    // list of files / patterns to load in the browser
    files: [
        JQUERY,
        {pattern: './mocks/ck.mock.js'},
        {pattern: JSTESTROOT + '**/*.spec.js'}
    ],


    // list of files to exclude
    exclude: [],

    // preprocess matching files before serving them to the browser
    // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
    preprocessors: {
        //'../../../docroot/res/js/app/**/*.js': [ 'coverage' ],
        //'../../../docroot/res/js/legacy/**/*.js': [ 'coverage' ],
        '../docroot/res/js/**/*.spec.js': ['webpack', 'sourcemap']
    },

    webpack: parseDevConfigToTestConfig(webpackConfig),

    webpackMiddleware: {
        stats: {
            colors: true
        }
    },

    // test results reporter to use
    // possible values: 'dots', 'progress'
    // available reporters: https://npmjs.org/browse/keyword/karma-reporter
    reporters: ['dots', 'coverage', 'junit', 'html'],

    // the default configuration
    htmlReporter: {
      outputDir: 'karma_html',
      templatePath: __dirname+'/htmlreport/jasmine_template.html'
    },

    coverageReporter: {
        dir : 'coverage/',
        reporters: [
            { type: 'html', subdir: 'report-html' },
            { type: 'cobertura', subdir: '.' },
            { type: 'cobertura' },
            { type: 'text-summary' }
        ]
    },

    junitReporter: {
        outputFile: 's.xml'
    },

    // web server port
    port: 8088,


    // enable / disable colors in the output (reporters and logs)
    colors: true,


    // level of logging
    // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
    logLevel: config.LOG_INFO,


    // enable / disable watching file and executing tests whenever any file changes
    autoWatch: true,


    // Start these browsers, currently available:
    // - Chrome
    // - ChromeCanary
    // - Firefox
    // - Opera
    // - Safari (only Mac)
    // - PhantomJS
    // - IE (only Windows)
    browsers: ['PhantomJS'],

    // Which plugins to enable
    plugins: [
        'karma-chrome-launcher',
        'karma-phantomjs-launcher',
        'karma-jasmine',
        'karma-coverage',
        'karma-junit-reporter',
        'karma-sourcemap-loader',
        'karma-webpack',
        'istanbul-instrumenter-loader',
        'karma-jasmine-html-reporter'
     ],

    // Continuous Integration mode
    // if true, Karma captures browsers, runs the tests and exits
    singleRun: true
  });
};

**Comment by nilni-ck** [comment]
Update, getting fixed since on jenkins, every test suite is runned under var/lib, which is excluded from the postloader logic there :pig_nose:

**Comment by areddy7021** [comment]
here is my karma conf

// Reference: http://karma-runner.github.io/0.12/config/configuration-file.html
module.exports = function karmaConfig (config) {
  config.set({
    frameworks: [
      // Reference: https://github.com/karma-runner/karma-jasmine
      // Set framework to jasmine
      'jasmine'
    ],

    reporters: [
      // Reference: https://github.com/mlex/karma-spec-reporter
      // Set reporter to print detailed results to console
      'progress',
        'verbose',
        'dots',

      // Reference: https://github.com/karma-runner/karma-coverage
      // Output code coverage files
      'coverage'
    ],

    files: [
      // Grab all files in the app folder that contain .spec.
      //'src/tests.webpack.js'
      'test/tests.webpack.js'
    ],

    preprocessors: {
      // Reference: http://webpack.github.io/docs/testing.html
      // Reference: https://github.com/webpack/karma-webpack
      // Convert files with webpack and load sourcemaps
      'test/tests.webpack.js': ['webpack', 'sourcemap']
    },

    browsers: [
      // Run tests using PhantomJS
      'PhantomJS'
    ],

    singleRun: true,

    // Configure code coverage reporter
    coverageReporter: {
      dir: 'coverage/',
      reporters: [
        {type: 'text-summary'},
        {type: 'html'}
      ]
    },

    webpack: require('./webpack.config'),

    // Hide webpack build information from output
    webpackMiddleware: {
      noInfo: 'errors-only'
    }
  });
};
