### ISSUE TITLE
No source map support

### ISSUE THREAD

**Issue by claydiffrient** [deepsweet/istanbul-instrumenter-loader#7]
When using this as a post loader in my webpack config:
```js
webpackConfig.module.postLoaders = [
  {
    test: /\.jsx$/,
    exclude: /(test|node_modules|bower_components)\//,
    loader: 'istanbul-instrumenter'
  }
];
```
It ends up destroying source maps: `devtool: 'source-map',`

For now my work around is to do 
```js
let istanbulInstrumenter =  {
    test: /\.jsx$/,
    exclude: /(test|node_modules|bower_components)\//,
    loader: 'istanbul-instrumenter'
  };
webpackConfig.module.postLoaders = IS_CI_ENV ? [istanbulInstrumenter] : []
```
Which works for when I want it to do coverage from my CI environment, but makes it so it's slightly more difficult to get coverage locally.

**Comment by deepsweet** [comment]
afaik there is no source maps support https://github.com/gotwarlost/istanbul/issues/212 + https://github.com/karma-runner/karma-coverage/issues/109, so there is nothing to return from the loader.

btw, are you sure that you really need source maps in case of code coverage?

**Comment by claydiffrient** [comment]
Fair point.

Well, I use the same webpack config for development and testing.  Maybe I should split that out instead.  The source maps I need for development, but the coverage I want as part of testing.  So having to comment out the instrumenter or provide a ENV variable is a bit cumbersome.

But yeah, I don't need source maps when doing coverage, feel free to close this issue.  The true thing for me to do is have my test environment load a different webpack config than my local environment.

**Comment by deepsweet** [comment]
usually I have 3 webpack configs inherited from "common" one: build, dev and test. so maybe it's a good moment to start splitting :)

**Comment by alexgorbatchev** [comment]
I think the sourcemap is now used to remap covered JS code back to original source it was transpiled from. With babel, typescript & angular 2 this is becoming a must have feature. See

* https://github.com/SitePen/remap-istanbul
* and a very long thread in istanbul repo on this subject https://github.com/gotwarlost/istanbul/issues/212

**Comment by asci** [comment]
+1 - new `babel` does not support correct `auxiliaryCommentBefore` - but supports source maps, as well as `istambul 1.0.0-alpha.2`

**Comment by viktornord** [comment]
`remap-istanbul` is great for getting html coverage report. But `text-summary` report still shows stats for the transpiled sources. How this can be fixed?
